homepage:
    resource: '@AppBundle/Controller/'
    type: annotation

genj_faq_faq_index:
    path:  /all-questions/{categorySlug}/{questionSlug}
    defaults: { _controller: GenjFaqBundle:Faq:index, categorySlug: null, questionSlug: null }

genj_faq_category_show:
    path:  /faq/{slug}
    defaults: { _controller: GenjFaqBundle:Category:show }

genj_faq_question_show:
    path:  /faq/{categorySlug}/{slug}
    defaults: { _controller: GenjFaqBundle:Question:show }