homepage:
    resource: '@AppBundle/Controller/'
    type: annotation

genj_faq_faq_index:
    path:  /faq/{categorySlug}/{questionSlug}
    defaults: { _controller: GenjFaqBundle:Faq:index, categorySlug: null, questionSlug: null }
